config/routes.rb
Rails.application.routes.draw do
  get 'weather/query'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/query_weather" => "weather#query", as: :query_weather_info
  get "/weather_info" => "weather#retrieve_weather_info", as: :retrieve_weather_info

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def query
  end

  def retrieve_weather_info
    address_info = params[:address]
    if address_info.blank?
      render "query", :locals => { error_msg: "Address is blank. Please enter valid address" } and return
    end

    zip_code_match = params[:address].match(/(\d+)$/)
    zip_code = ""
    if zip_code_match && zip_code_match[1]
      zip_code = zip_code_match[1]
    end
    @info = WeatherData.new(zip_code, params[:unit])
    render "weather/retrieve_weather_info"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppleWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/query.html.erb
<h3>Enter address ending in zipcode to get weather info</h3>
<%= form_with url: retrieve_weather_info_path, local: true, method: :get do %>
  <% if local_assigns.has_key? :error_msg %>
    <p class="error"><%= error_msg %></p>
  <% end %>
  Unit:
  <%= radio_button_tag 'unit', 'fahrenheit', true %>Fahrenheit
  <%= radio_button_tag 'unit', 'celsius' %>Celsius
  <br>
  <%= label_tag "address" %>
  <%= text_field_tag "address", nil %>
  <br>
  <%= submit_tag "Retrieve weather info" %>
<% end %>

app/views/weather/retrieve_weather_info.html.erb
<h3>Weather info for your address</h3>
<% weather_data = @info.data %>
<% if weather_data[:error] %>
An error occured
<p class="error"><%= weather_data[:error] %></p>
<% else %>
Unit: <%= @info.unit.capitalize %><br/>
<% current_data = weather_data[:current_data] %>
Location: <%= current_data[:location][:name]%>, <%=current_data[:location][:region] %></br>
Weather: <%= current_data[:temp] %></br>
Condition: <%= current_data[:condition] %></br>
Feels Like: <%= current_data[:feelslike] %></br>
<% forecast_data = weather_data[:forecast_data] %>
<h3>Weather forecast for upcoming days</h3>
<table>
  <tr>
   <th>Date</th>
   <th>Max Temperature</th>
   <th>Min Temperature</th>
  </tr>
  <% forecast_data.each do |d| %>
  <tr>
    <td><%= d[:date] %></td>
    <td><%= d[:maxtemp] %></td>
    <td><%= d[:mintemp] %></td>
  </tr>
 <% end %>
</table>
<% if @info.cached %>
Note: Data pulled within last 30 minutes<br/>
<% else %>
Note: Data pulled just now<br/>
<% end %>
<% end %>
<a href="/query_weather">Back to query form</a>